/**
 * Wiki Details → sim overrides for champions beyond the core interaction table.
 * Generated by scripts/gen-wiki-pass-overrides.mjs — edit the script and re-run to bulk-update.
 */
import type { ChampionInteractionProfile } from "./abilityInteractions";

export const CHAMPION_WIKI_PASS_OVERRIDES: Record<
  string,
  Partial<ChampionInteractionProfile>
> = {
  Aatrox: {
    missingHPBonusADMax: 20,
    sustainedBonusAttackSpeedPercent: 15,
  },
  Ahri: {
    sustainedBonusAttackSpeedPercent: 0,
  },
  Akshan: {
    sustainedBonusAttackSpeedPercent: 25,
  },
  Alistar: {},
  Ambessa: {
    sustainedBonusAttackSpeedPercent: 18,
  },
  Amumu: {},
  Anivia: {
    sustainedBonusAttackSpeedPercent: 0,
  },
  Annie: {},
  Aphelios: {
    ammoCycleDamageMultiplier: 1.2,
    sustainedBonusAttackSpeedPercent: 15,
  },
  Ashe: {
    passiveCritDamageBonusScale: 1.35,
    sustainedBonusAttackSpeedPercent: 22,
  },
  AurelionSol: {
    sustainedBonusAttackSpeedPercent: 0,
  },
  Aurora: {
    sustainedBonusAttackSpeedPercent: 10,
  },
  Azir: {
    sustainedBonusAttackSpeedPercent: 5,
  },
  Bard: {
    sustainedBonusAttackSpeedPercent: 12,
  },
  Blitzcrank: {},
  Braum: {},
  Briar: {
    sustainedBonusAttackSpeedPercent: 35,
  },
  Caitlyn: {},
  Camille: {
    everyNthHitTrueMaxHPPercent: 4,
    everyNthHit: 2,
  },
  Cassiopeia: {
    ablazeAbilityDamageAmp: 1.35,
  },
  ChoGath: {
    everyNthHitTrueMaxHPPercent: 4,
    everyNthHit: 3,
  },
  Diana: {
    sustainedBonusAttackSpeedPercent: 18,
  },
  DrMundo: {
    missingHPBonusADMax: 20,
  },
  Ekko: {
    everyNthHitTrueMaxHPPercent: 6,
    everyNthHit: 3,
    assumeComboKill: false,
  },
  Elise: {
    sustainedBonusAttackSpeedPercent: 15,
  },
  Evelynn: {
    assumeComboKill: true,
  },
  Fiddlesticks: {},
  Fiora: {},
  Fizz: {
    sustainedBonusAttackSpeedPercent: 12,
  },
  Galio: {},
  Garen: {
    sustainedBonusAttackSpeedPercent: 10,
  },
  Gragas: {},
  Hecarim: {
    sustainedBonusAttackSpeedPercent: 15,
  },
  Heimerdinger: {},
  Hwei: {
    sustainedBonusAttackSpeedPercent: 0,
  },
  Illaoi: {
    abilityHitMultipliers: {
      "Harsh Lesson": 1.8,
    },
  },
  Ivern: {},
  Janna: {},
  Jayce: {
    sustainedBonusAttackSpeedPercent: 12,
  },
  Jhin: {
    passiveCritDamageBonusScale: 0.75,
    averagePassiveCritChancePercent: 25,
    ammoCycleDamageMultiplier: 1.12,
  },
  Jinx: {
    sustainedBonusAttackSpeedPercent: 65,
  },
  KaiSa: {
    sustainedBonusAttackSpeedPercent: 45,
    abilityCooldownMultiplier: {
      E: 0.72,
    },
  },
  Kalista: {
    autoAttackDamageMultiplier: 0.9,
    bonusAttackSpeedScale: 0.75,
    abilityCooldownMultiplier: {
      E: 0.85,
    },
  },
  Karma: {},
  Karthus: {
    isolatedDamageMultiplier: 1.65,
  },
  Kassadin: {
    sustainedBonusAttackSpeedPercent: 8,
  },
  Katarina: {
    assumeComboKill: true,
  },
  Kennen: {
    sustainedBonusAttackSpeedPercent: 12,
  },
  Kindred: {
    sustainedBonusAttackSpeedPercent: 25,
  },
  Kled: {
    sustainedBonusAttackSpeedPercent: 20,
  },
  KogMaw: {
    sustainedBonusAttackSpeedPercent: 20,
    passiveArmorPenPercent: 22,
  },
  LeeSin: {
    assumeComboKill: true,
  },
  Leona: {},
  Lillia: {
    blazeDotPerStackMaxHPPercent: 1,
    averageBlazeStacks: 2,
  },
  Lissandra: {},
  Lulu: {},
  Lux: {
    sustainedBonusAttackSpeedPercent: 0,
  },
  Malphite: {},
  Maokai: {},
  MasterYi: {
    sustainedBonusAttackSpeedPercent: 30,
  },
  Mel: {},
  Milio: {},
  Mordekaiser: {
    sustainedBonusAttackSpeedPercent: 8,
  },
  Morgana: {},
  Naafiri: {
    assumeComboKill: true,
  },
  Nami: {},
  Nautilus: {},
  Neeko: {},
  Nidalee: {
    assumeComboKill: true,
    isolatedDamageMultiplier: 1.5,
  },
  Nilah: {
    passiveArmorPenPercent: 15,
    sustainedBonusAttackSpeedPercent: 25,
    abilityCooldownMultiplier: {
      Q: 0.55,
    },
  },
  Nocturne: {
    sustainedBonusAttackSpeedPercent: 22,
  },
  Nunu: {},
  Olaf: {
    missingHPBonusADMax: 25,
    sustainedBonusAttackSpeedPercent: 20,
  },
  Orianna: {
    sustainedBonusAttackSpeedPercent: 0,
  },
  Ornn: {
    sustainedBonusAttackSpeedPercent: 5,
  },
  Pantheon: {
    sustainedBonusAttackSpeedPercent: 14,
  },
  Poppy: {},
  Pyke: {
    assumeComboKill: true,
    missingHPBonusADMax: 18,
  },
  Qiyana: {
    assumeComboKill: true,
  },
  Quinn: {
    sustainedBonusAttackSpeedPercent: 25,
  },
  Rammus: {},
  RekSai: {
    sustainedBonusAttackSpeedPercent: 12,
  },
  Rell: {},
  Renata: {},
  Renekton: {
    sustainedBonusAttackSpeedPercent: 12,
  },
  Rengar: {
    sustainedBonusAttackSpeedPercent: 20,
    passiveArmorPenPercent: 12,
  },
  Riven: {
    sustainedBonusAttackSpeedPercent: 18,
  },
  Rumble: {
    blazeDotPerStackMaxHPPercent: 1.2,
    averageBlazeStacks: 1,
  },
  Ryze: {
    sustainedBonusAttackSpeedPercent: 5,
  },
  Sejuani: {},
  Senna: {
    sustainedBonusAttackSpeedPercent: 8,
  },
  Seraphine: {},
  Sett: {
    missingHPBonusADMax: 22,
  },
  Shaco: {
    assumeComboKill: true,
  },
  Shen: {},
  Shyvana: {
    sustainedBonusAttackSpeedPercent: 18,
    blazeDotPerStackMaxHPPercent: 1.5,
    averageBlazeStacks: 1,
  },
  Singed: {
    toggleDotUptime: 0.85,
  },
  Sion: {
    ultimateBonusHP: 400,
    ultimateBonusHPUptime: 0.25,
  },
  Skarner: {},
  Sona: {},
  Soraka: {},
  Swain: {
    abilityHitMultipliers: {
      "Vision of Empire": 1.85,
    },
  },
  Sylas: {
    sustainedBonusAttackSpeedPercent: 10,
  },
  Syndra: {
    sustainedBonusAttackSpeedPercent: 0,
  },
  TahmKench: {},
  Taliyah: {
    sustainedBonusAttackSpeedPercent: 8,
  },
  Taric: {},
  Teemo: {
    stackDotBasePerSecond: 12,
    stackDotAPRatioPerSecond: 10,
    averageDotStacks: 1,
  },
  Thresh: {
    abilityHitMultipliers: {
      "Death Sentence": 1.5,
    },
  },
  Trundle: {
    sustainedBonusAttackSpeedPercent: 12,
  },
  TwistedFate: {
    sustainedBonusAttackSpeedPercent: 18,
  },
  Twitch: {
    sustainedBonusAttackSpeedPercent: 35,
    stackDotBasePerSecond: 4,
    stackDotAPRatioPerSecond: 3,
    averageDotStacks: 4,
    stackDotDamageType: "true",
  },
  Udyr: {
    sustainedBonusAttackSpeedPercent: 20,
  },
  Urgot: {
    sustainedBonusAttackSpeedPercent: 10,
  },
  Varus: {
    sustainedBonusAttackSpeedPercent: 12,
    explosiveChargeStackMultiplier: 2.2,
  },
  Vayne: {
    everyNthHitTrueMaxHPPercent: 12,
    everyNthHit: 3,
  },
  Veigar: {},
  VelKoz: {
    everyNthHitTrueMaxHPPercent: 8,
    everyNthHit: 3,
    abilityHitMultipliers: {
      "Life Form Disintegration Ray": 1.4,
    },
  },
  Vex: {},
  Vi: {
    sustainedBonusAttackSpeedPercent: 12,
  },
  Viktor: {
    sustainedBonusAttackSpeedPercent: 0,
  },
  Vladimir: {
    sustainedBonusAttackSpeedPercent: 5,
  },
  Volibear: {
    sustainedBonusAttackSpeedPercent: 14,
  },
  Warwick: {
    sustainedBonusAttackSpeedPercent: 25,
  },
  Wukong: {
    sustainedBonusAttackSpeedPercent: 22,
  },
  Xayah: {
    postAbilityEmpoweredAutoAdPercent: 45,
    postAbilityEmpoweredUptime: 0.35,
    sustainedBonusAttackSpeedPercent: 42,
    abilityHitMultipliers: {
      Bladecaller: 2.5,
    },
  },
  Xerath: {
    sustainedBonusAttackSpeedPercent: 0,
  },
  XinZhao: {
    sustainedBonusAttackSpeedPercent: 16,
  },
  Yorick: {
    sustainedBonusAttackSpeedPercent: 8,
  },
  Yuumi: {},
  Zaahen: {
    sustainedBonusAttackSpeedPercent: 15,
  },
  Zac: {},
  Zeri: {
    autoAttackDamageMultiplier: 0.15,
    sustainedBonusAttackSpeedPercent: 10,
  },
  Ziggs: {},
  Zilean: {},
  Zoe: {
    sustainedBonusAttackSpeedPercent: 0,
  },
  Zyra: {
    blazeDotPerStackMaxHPPercent: 0.8,
    averageBlazeStacks: 2,
  },
};
